apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-cicd-demo
  labels:
    app: azure-devops-cicd-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azure-devops-cicd-demo
  template:
    metadata:
      labels:
        app: azure-devops-cicd-demo
    spec:
      containers:
      - name: azure-devops-cicd-demo
        image: <your-docker-image>:<tag>
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"